import os

YOUR_CHANNEL_ACCESS_TOKEN = os.environ["YOUR_CHANNEL_ACCESS_TOKEN"]
YOUR_CHANNEL_SECRET = os.environ["YOUR_CHANNEL_SECRET"]
ELMS_STUDENT_ID = os.environ["ELMS_STUDENT_ID"]
ELMS_PASSWORD = os.environ["ELMS_PASSWORD"]
LINE_USER_ID = os.environ["LINE_USER_ID"]
