import os

LINE_CHANNEL_ACCESS_TOKEN = os.environ["LINE_CHANNEL_ACCESS_TOKEN"]
LINE_CHANNEL_SECRET = os.environ["LINE_CHANNEL_SECRET"]
LINE_USER_ID = os.environ["LINE_USER_ID"]
ELMS_STUDENT_ID = os.environ["ELMS_STUDENT_ID"]
ELMS_PASSWORD = os.environ["ELMS_PASSWORD"]
INTERVAL_MINUTES = 10
