import os

YOUR_CHANNEL_ACCESS_TOKEN = os.environ["YOUR_CHANNEL_ACCESS_TOKEN"]
YOUR_CHANNEL_SECRET = os.environ["YOUR_CHANNEL_SECRET"]
ELMS_STUDENT_ID = "dummy"
ELMS_PASSWORD = "dummy"
LINE_USER_ID = "dummy"
